services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.3.6
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://127.0.0.1:8545"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    # Intentional hack to have all params in a single string, otherwise arguments go to `sh -c` and not into anvil
    command: ["anvil --port 8545 --block-time 5"]
    ports:
      - "8545:8545"

  hyperlane-core-deploy:
    image: ghcr.io/sovereign-labs/hyperlane-cli:sov-integration-3
    depends_on:
      anvil:
        condition: service_healthy
    environment:
      # Anvil account 0 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - HYP_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    volumes:
      - ./configs:/configs
    command: >
      core deploy
      --registry /configs
      --disableProxy
      --config /configs/core-config.yaml
      --chain ethtest
      --yes

  hyperlane-warp-deploy:
    image: ghcr.io/sovereign-labs/hyperlane-cli:sov-integration-3
    depends_on:
      hyperlane-core-deploy:
        condition: service_completed_successfully
    environment:
      # Anvil account 0 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - HYP_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    volumes:
      - ./configs:/configs
    command: >
      warp deploy
      --registry /configs
      --disableProxy
      --config /configs/warp-route-deployment.yaml
      --yes


  validator-ethtest:
    image: ghcr.io/sovereign-labs/hyperlane-agent:integration-8a
    depends_on:
      hyperlane-warp-deploy:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CONFIG_FILES=/configs/agent-config.json
      # Anvil account 1 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
      - HYP_VALIDATOR_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      # minter_private_key.json
      - HYP_CHAINS_SOVSTARTER_SIGNER_KEY=0x0d87c12ea7c12024b3f70a26d735874608f17c8bce2b48e6fe87389310191264
      - NO_COLOR=1
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "test -f /ethtest-validator-signatures/announcement.json" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s
    volumes:
      - ./configs:/configs:ro
      - ./docker-data/validator-ethtest:/hyperlane_db:rw
      - ./docker-data/validator-ethtest/signatures:/ethtest-validator-signatures:rw
    ports:
      - "9092:9092"
    command: >
      /app/validator
      --db /hyperlane_db
      --originChainName ethtest 
      --chains.sovstarter.signer.type "sovereignKey"
      --chains.sovstarter.signer.accountType "ethereum"
      --checkpointSyncer.type localStorage
      --checkpointSyncer.path /ethtest-validator-signatures
      --metrics-port 9092
      --log.level debug
      --log.format "pretty"

  # TODO: validator-sovstarter

  relayer:
    image: ghcr.io/sovereign-labs/hyperlane-agent:integration-8a
    depends_on:
      hyperlane-warp-deploy:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CONFIG_FILES=/configs/agent-config.json
      # Anvil account 2 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
      - HYP_CHAINS_ETHTEST_SIGNER_KEY=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
      # token_deployer.json
      - HYP_CHAINS_SOVSTARTER_SIGNER_KEY=0x0187c12ea7c12024b3f70ac5d73587463af17c8bce2bd9e6fe87389310196c64
      - NO_COLOR=1
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "test -d /hyperlane_db && test -f /hyperlane_db/CURRENT"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s
    volumes:
      - ./configs:/configs:ro
      - ./docker-data/relayer:/hyperlane_db:rw
      - ./docker-data/validator-ethtest/signatures:/ethtest-validator-signatures:ro
    ports:
      - "9091:9091"
    # Option to consider: --gasPaymentEnforcement '[{"type":"none"}]'
    command: >
      /app/relayer
      --db /hyperlane_db
      --allowLocalCheckpointSyncers true
      --relayChains sovstarter,ethtest
      --chains.sovstarter.signer.type "sovereignKey"
      --chains.sovstarter.signer.accountType "ethereum"
      --metrics-port 9091
      --log.level debug
      --log.format "pretty"

  # Utility service for running hyperlane-cli commands
  hyperlane-cli:
    image: ghcr.io/sovereign-labs/hyperlane-cli:sov-integration-3
    profiles: ["cli"]
    depends_on:
      anvil:
        condition: service_healthy
    volumes:
      - ./configs:/configs:ro
    command: ["echo", "This service is used for running CLI commands"]
