version: "3.8"

services:
  validator:
    env_file: .env
    image: hyperlane:latest # Requires a local build of hyperlane from the eiger hyperlane monorepo. Reach out to the sov team for help
    container_name: hyperlane-validator-sovstarter-solana-testnet
    restart: unless-stopped
    environment:
      # CONFIG_FILES is used internally by the agent entrypoint script
      - CONFIG_FILES=/configs/agent-config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount the interpolated agent configuration
      - ./config.json:/configs/agent-config.json:ro
      # Mount persistent storage for the validator database
      - ./docker-data/validator:/hyperlane_db
      # Mount the shared volume for validator signatures
      - ./docker-data/validator/signatures:/validator-signatures
    # Note: If your rollup runs in Docker, add 'depends_on' and ensure network connectivity.
    command: >
      validator
      --db /hyperlane_db
      --originChainName sovstarter
      --checkpointSyncer.type localStorage
      --checkpointSyncer.path /validator-signatures
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  relayer:
    env_file: .env
    image: hyperlane:latest # Requires a local build of hyperlane from the eiger hyperlane monorepo. Reach out to the sov team for help
    container_name: hyperlane-relayer-sovstarter-solana-testnet
    restart: unless-stopped
    ports:
      - "9091:9091"
    environment:
      # CONFIG_FILES is used internally by the agent entrypoint script
      - CONFIG_FILES=/configs/agent-config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount the interpolated agent configuration
      - ./config.json:/configs/agent-config.json:ro
      # Mount persistent storage for the relayer database
      - ./docker-data/relayer:/hyperlane_db
      # Mount the shared volume for validator signatures (read-only)
      - ./docker-data/validator/signatures:/validator-signatures:ro
      # Mount the shared volume for chain configurations
      - ./configs/chains:/root/.hyperlane/chains:ro
    # Note: If your rollup runs in Docker, add 'depends_on' and ensure network connectivity.
    command: >
      relayer
      --db /hyperlane_db
      --relayChains sovstarter,solanatestnet
      --allowLocalCheckpointSyncers true
      --metrics-port 9091
      --gasPaymentEnforcement '[{"type":"none"}]'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  validator-signatures:
    driver: local
