chainId: 31337
displayName: EthTest
domainId: 3133790210
isTestnet: true
name: ethtest
nativeToken:
  decimals: 18
  name: Ether
  symbol: ETH
protocol: ethereum
rpcUrls:
    - http: http://anvil:8545